### PR TITLE
rename proto to avoid namespace conflicts when importing v1+v2

### PR DESCRIPTION
**Pull request by shyba**
feel free to pick another name, we just cant have two "claim.proto" as it conflicts

### CODE REVIEW

**Comment by lyoshenka** [comment]
whats the actual problem. is it the filename or the class names?

**Comment by shyba** [comment]
just the file name (it picks the file name as the proto name on generated code; We dont use it but protobuf complains when you import two with the same name)

**Comment by lyoshenka** [comment]
can we change v1 instead of v2? or does v1 need to stay as it is?

do we need to change `pb` -> `pb3`?

**Comment by shyba** [comment]
changed v1 file name and package. Yes, the package conflicts too because the class names are the same.
v1 claim.proto is now legacy_claim.proto and package is legacy_pb instead of pb

**Pull request closed without merging**
