### PR TITLE
Add C++ protobuf generated code

### LINKED ISSUE #4: Generate C++ protobuf code
We already have python, JS, and Go. C++ is our last major language that's missing.

### PR DESCRIPTION
**Pull request by qiell**
```
protoc --proto_path=proto --cpp_out=cpp/ proto/certificate.proto proto/claim.proto proto/fee.proto proto/metadata.proto proto/signature.proto proto/source.proto proto/stream.proto
```

Signed-off-by: Akash Srivastava <akash.srivastava@openebs.io>

fixes: #4

### CODE REVIEW

**Comment by bvbfan** [comment]
Can you update bash script as well, it has check for minimum version.
https://github.com/lbryio/types/blob/master/build.sh#L30

**Comment by qiell** [comment]
Sure @bvbfan , I'll update it :)

**Comment by qiell** [comment]
@bvbfan Updated the bash file.

**Comment by tzarebczan** [comment]
@Akash4927 Thanks for the contribution! Can we send you some [LBC in appreciation](https://lbry.io/faq/tips)?

**Comment by qiell** [comment]
@tzarebczan That'll be great :smiley: 
Looking forward to contribute more

**Comment by lyoshenka** [comment]
could you change the dir name from `c++` to `cpp`, add it to line 27 too. using pluses in dir names can cause issues down the road. other than that, looks good to me. thanks!

**Comment by qiell** [comment]
Sure @lyoshenka

**Comment by qiell** [comment]
@lyoshenka Thanks :)

**Comment by lyoshenka** [comment]
thanks @Akash4927. let me know if you're interested in contributing in any other way. i'd be happy to help you find something cool and/or challenging.

**Pull request merged**
