### PR TITLE
new proto3 definitions

### LINKED ISSUE #3: Upgrade protobuf to proto3
@lyoshenka commented on [Tue Jan 23 2018](https://github.com/lbryio/lbryschema/issues/36)

---

@lyoshenka commented on [Mon Sep 17 2018](https://github.com/lbryio/lbryschema/issues/36#issuecomment-422119009)

moving to types repo since this repo will probably disappear before this happens

### LINKED ISSUE #6: Rename content_type to media_type
`media_type` is the specific term for the property being provided.

`content_type` is a legacy term that is used because HTTP uses it.

https://stackoverflow.com/questions/9258108/whats-the-difference-between-mediatype-contenttype-and-mimetype

### LINKED ISSUE #8: Add channel related metadata columns
At a minimum:

1) Name
2) Thumbnail
3) Cover
4) Description

Other considerations:
1) Primary Language
2) Featured video
3) Other channels 
4) Playlists?

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

### LINKED ISSUE #13: Add releaseTime to schema

### LINKED ISSUE #16: Add tags to schema
We should allow publishers to set tags for their uploaded content. Would need to discuss implementation details, for example, how many tags do we allow and how is it stored in the metadata. If we want community overlays to work properly, each tag may need to exist on its own, as opposed to a list of tags.

### PR DESCRIPTION
**Pull request by lyoshenka**
Final proto3 PR.

Closes #3, closes #16, closes #8, closes #13, closes #6, closes #17, closes lbryio/internal-issues#205.

### CODE REVIEW

**Comment by lyoshenka** [comment]
One issue that was discussed a lot in #17 is urls vs claim ids. I stuck with urls for now because there are outstanding questions about claim ids. For example, if a thumbnail is at a claim with a fee, what do you do? Pay the fee? Not show the thumbnail? Ask the user? What if the fee is high? etc.

We can add `thumbnail_claim_id` later.

**Review by shyba — APPROVED** [review]

**Comment by eukreign** [comment]
_"For example, if a thumbnail is at a claim with a fee, what do you do? Pay the fee? Not show the thumbnail? Ask the user? What if the fee is high? etc."_
Show broken/missing icon placeholder.

**Comment by lyoshenka** [comment]
what if its 0.0000001 LBC for the thumbnail?

**Comment by eukreign** [comment]
What's the use case? Why would it make sense to charge people to show a thumbnail?

I think if it requires payment it's a broken/invalid thumbnail.

**Comment by eukreign** [comment]
@lyoshenka I would like to reiterate the two things I still think would be really good to add/change:

1. Drop the `Claim` container type, if you have to do a check on what type of claim it is anyways then the same check can be done when extracting the protobuf data from the claim transaction. Having a claim (protobuf type) within a claim (tx) seems like an extraneous layer of indirection.

2. Once we start requiring `identities` for users in order to participate in commenting and possibly other activities on the LBRY network it's likely that these `identity` certificates will significantly outpace the number of `channels`. If `Certificate` is not desirable name, can we at least change `channel` to `identity` if 90% of these types of claims will be user identity certificates? Referring to user identities as `channels` just seems weird.

**Comment by kauffj** [comment]
@lyoshenka I proposed that for images we use either stream hashes or blob hashes, not claim ids. How often are images larger than 2MB, and do we want to support > 2MB images anyway? If not, blob hash works fine and doesn't require blockchain bloat for additional claims.

**Comment by eukreign** [comment]
@kauffj A downside of not having a `claim` for the thumbnail is that when blob hosts want to purge invalid / abandoned blobs the method to figure out which blobs are still valid and which aren't would be more complicated: You can't just say "only keep blobs which are represented by valid calims on the blockchain" now you have to separately search for blob hashes in the metadata. The other downside is blob size but you could probably point to an sd_blob and therefore not have blob size limitation.

On the positive side:
1. it's measurably faster
2. eliminates the situation where someone tries to charge for thumbnail

**Comment by kauffj** [comment]
@eukreign fair point. Two further comments:

1) It's not trivial to identify which blobs appear in valid claims. To do this, one must fetching all stream descriptor blobs. This seems as or more complicated than checking which blobs appear in the blockchain.
2) I suspect blob retention will probably eventually be done by comparing access rates with hosting density, rather than simply trying to host everything.

**Pull request merged**
